server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
      
      
turbine:
  appConfig: activationService
  clusterNameExpression: new String('default')